name: Project CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci

      - name: Create env file for ContentfulCMS
        run: |
          echo CONTENTFUL_ACCESS_TOKEN="$CONTENTFUL_ACCESS_TOKEN" >> .env
          echo CONTENTFUL_SPACE_ID="$CONTENTFUL_SPACE_ID " >> .env
          echo MAILCHIMP_ENDPOINT="$MAILCHIMP_ENDPOINT" >> .env

      - run: npm run build
