name: Project CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Create env file for ContentfulCMS
        run: |
          cat << EOF > .env
          CONTENTFUL_ACCESS_TOKEN='${{ secrets.CONTENTFUL_ACCESS_TOKEN }}'
          CONTENTFUL_SPACE_ID='${{ secrets.CONTENTFUL_SPACE_ID }}'
          MAILCHIMP_ENDPOINT='${{ secrets.MAILCHIMP_ENDPOINT }}'
          EOF

      - run: npm run build
  preview:
    name: Preview
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: prod
          work-dir: ./pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - run: pip install -r requirements.txt
        working-directory: ./pulumi
