name: Project CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci

      - name: Create env file for ContentfulCMS
        run: |
          cat << EOF > .env
          CONTENTFUL_ACCESS_TOKEN='${{ secrets.CONTENTFUL_ACCESS_TOKEN }}'
          CONTENTFUL_SPACE_ID='${{ secrets.CONTENTFUL_SPACE_ID }}'
          MAILCHIMP_ENDPOINT='${{ secrets.MAILCHIMP_ENDPOINT }}'
          EOF
          cat .env

      # - run: npm run build
