name: PR CI

on:
  pull_request:
    branches: ["**"]

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create env file for ContentfulCMS
        run: |
          cat << EOF > .env
          CONTENTFUL_ACCESS_TOKEN='${{ secrets.CONTENTFUL_ACCESS_TOKEN }}'
          CONTENTFUL_SPACE_ID='${{ secrets.CONTENTFUL_SPACE_ID }}'
          MAILCHIMP_ENDPOINT='${{ secrets.MAILCHIMP_ENDPOINT }}'
          EOF

      - run: npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: website
          path: public

  preview:
    name: Preview
    environment: prod
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: python3 -m venv venv
        working-directory: ./pulumi

      - run: |
          source venv/bin/activate
          pip install -r requirements.txt
          deactivate
        working-directory: ./pulumi

      - uses: actions/download-artifact@v2
        with:
          name: website
          path: public

      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: prod
          work-dir: ./pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
